text_extensions: [ 'css', 'erb', 'haml', 'htm', 'html', 'js', 'less', 'markdown', 'md', 'php', 'rb', 'sass', 'scss', 'txt', 'xhtml', 'xml' ]
output_dir: output
index_filenames: [ 'index.html' ]
enable_output_diff: false
site:
  title: "Genomer"
  subtitle: "A Swiss army knife for genome projects"
  url: "http://next.gs"
  favicon: "/images/favicon.ico"
  analytics_token: "UA-1362555-4"
  navigation:
    'about':           "/"
    'install':         "/install/"
    'using plugins':   "/using-plugins/"
    'scaffold format': "/scaffold-format/"
    'troubleshooting': "/troubleshooting/"
    'mailing list':    "/mailing-list/"
    'contribute':      "/contribute/"
author:
  url: "http://www.michaelbarton.me.uk"
  name: "Michael Barton"
scripts:
  - "/javascript/scale.js"
stylesheets:
  "/stylesheets/styles.css": "screen,projection"
  "/stylesheets/pygment_trac.css": "screen,projection"
